# Generated by Django 4.2.7 on 2024-01-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phoneno', models.BigIntegerField()),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('res_name', models.CharField(max_length=200)),
                ('res_address', models.CharField(max_length=500)),
                ('res_contact', models.BigIntegerField()),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserveatapp.resadmin')),
            ],
        ),
        migrations.CreateModel(
            name='tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableno', models.IntegerField()),
                ('seating_capacity', models.IntegerField()),
                ('booking_status', models.BooleanField(default=False)),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserveatapp.restaurant')),
            ],
        ),
    ]
