# Generated by Django 4.2.7 on 2024-01-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserveatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('booked_for', models.DateField()),
                ('booking_time', models.TimeField()),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserveatapp.users')),
                ('restaurantid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserveatapp.restaurant')),
                ('tableid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserveatapp.tables')),
            ],
        ),
    ]
