# Generated by Django 4.2.7 on 2024-01-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserveatapp', '0002_remove_restaurant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambianceimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('resid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserveatapp.restaurant')),
            ],
        ),
    ]
