# Generated by Django 4.2.7 on 2024-01-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserveatapp', '0002_rename_regadmin_resadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=200)),
                ('res_address', models.CharField(max_length=500)),
                ('res_contact', models.BigIntegerField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserveatapp.resadmin')),
            ],
        ),
        migrations.CreateModel(
            name='tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablen0', models.IntegerField()),
                ('seating_capacity', models.IntegerField()),
                ('booking_status', models.BooleanField(default=False)),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserveatapp.restaurant')),
            ],
        ),
    ]
