# Generated by Django 4.2.7 on 2024-01-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveatapp', '0002_bookings_bookingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_status',
            field=models.CharField(default='Confirmed', max_length=200),
        ),
    ]
