# Generated by Django 4.2.7 on 2024-01-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveatapp', '0002_restaurant_tables_bookings_ambianceimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='booking_status',
            field=models.CharField(default='Available', max_length=200),
        ),
    ]
