# Generated by Django 4.2.7 on 2024-01-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveatapp', '0003_alter_tables_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='booking_status',
            field=models.CharField(default='Not Booked', max_length=200),
        ),
    ]
