# Generated by Django 4.2.7 on 2024-01-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveatapp', '0003_ambianceimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambianceimg',
            name='image',
            field=models.ImageField(upload_to='ambiance_images/'),
        ),
    ]
