# Generated by Django 4.2.7 on 2024-01-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveatapp', '0003_bookings_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='payment_model',
            field=models.CharField(choices=[('Cash', 'Cash'), ('PayPal', 'PayPal')], default='Cash', max_length=200),
        ),
        migrations.AddField(
            model_name='bookings',
            name='transaction_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
